# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: irenejoy21testapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: productService

provider:
  name: aws
  runtime: nodejs24.x
  # STEP 10
  httpApi:
    authorizers:
      myCognitoAuth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_W60RMNZ1Y
        audience: 
          - 75gmpfq557c7khpelrdmdgpgh6
  # END STEP 10
  # "region" specifies the AWS region where your service will be deployed.
  # STEP 2
  environment:
    BUCKET_NAME: products-images-irenejoy21-dev-12-new
    DYNAMODB_TABLE: Products
    # STEP 9
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:660880134927:Product-cleanup-topic
    # END STEP 9
  # END STEP 2
  # STEP 4
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:PutItem'
        # STEP 7
        - 'dynamodb:UpdateItem'
        - 'dynamodb:Scan'
        # END STEP 7
        # STEP 12
        - 'dynamodb:DeleteItem'
        # END STEP 12
      Resource: arn:aws:dynamodb:us-east-1:660880134927:table/Products
  # STEP 5
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource: arn:aws:s3:::products-images-irenejoy21-dev-12-new/*
  #  END STEP 5
  # END STEP 4 
  # STEP 13 
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: arn:aws:sns:us-east-1:660880134927:Product-cleanup-topic
  # END STEP 13
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

# STEP 1
resources:
  Resources:
    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: products-images-irenejoy21-dev-12-new 
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S #string
        KeySchema:
          - AttributeName: id
            KeyType: HASH #partition key
# STEP 9
    ProductCleanupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: Product-cleanup-topic
    ProductCleanupSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:us-east-1:660880134927:Product-cleanup-topic
        Protocol: email
        Endpoint: cefriantrinchera21@gmail.com
# END STEP 9
# END STEP 1
functions:
# STEP 3
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
          # STEP 11
          authorizer: 
            name: myCognitoAuth
          # END STEP 11
# END STEP 3
# STEP 8
  updateProductImage:
    handler: handlers/updateProductImage.updateProductImage
    events:
      - s3:
          bucket: products-images-irenejoy21-dev-12-new
          event: s3:ObjectCreated:*
          existing: true
  cleanupProducts:
    handler: handlers/cleanupProducts.cleanupProducts
    events:
      - schedule:
          rate: rate(2 minutes)
          enabled: true
# END STEP 8
  checkProductImage:
    handler: handlers/checkProductImage.checkProductImage
    events:
      - httpApi:
          path: /check-product-image
          method: get

