# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: irenejoy21testapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: productService

provider:
  name: aws
  runtime: nodejs24.x
  # "region" specifies the AWS region where your service will be deployed.
  # STEP 2
  environment:
    BUCKET_NAME: products-images-irenejoy21-dev-12-new
    DYNAMODB_TABLE: Products
  # END STEP 2
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

# STEP 1
resources:
  Resources:
    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: products-images-irenejoy21-dev-12-new 
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S #string
        KeySchema:
          - AttributeName: id
            KeyType: HASH #partition key
# END STEP ONE
functions:
# STEP 3
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
# END STEP 3
